/** Turns an analysis into a Markdown report a developer can paste into an issue or PR. */
export function toMarkdown({ metrics, rubric, review, analyzedAt }) {
  const { repo, social, languages } = metrics;
  const lines = [];

  lines.push(`# GitGrade report: ${repo.slug}`, "");
  lines.push(`**Score: ${rubric.score}/100 (${rubric.grade} - ${rubric.gradeLabel})**`, "");
  if (repo.description) lines.push(`> ${repo.description}`, "");

  lines.push(
    `- Stars: ${social.stars} | Forks: ${social.forks} | Contributors: ${social.contributors ?? "?"}`,
    `- Language: ${languages[0]?.name ?? "unknown"} | License: ${repo.license ?? "none"}`,
    `- Last push: ${repo.daysSincePush} days ago`,
    `- Analysed: ${new Date(analyzedAt).toLocaleString()}`,
    ""
  );

  if (review?.verdict) lines.push(`## Verdict`, "", review.verdict, "");

  if (review?.strengths?.length) {
    lines.push("## Strengths", "", ...review.strengths.map((item) => `- ${item}`), "");
  }
  if (review?.weaknesses?.length) {
    lines.push("## Weaknesses", "", ...review.weaknesses.map((item) => `- ${item}`), "");
  }

  if (review?.roadmap?.length) {
    lines.push("## Roadmap", "");
    review.roadmap.forEach((item, index) => {
      lines.push(`${index + 1}. **${item.title}** (${item.effort} effort, ${item.impact} impact)`);
      lines.push(`   ${item.why}`);
    });
    lines.push("");
  }

  lines.push("## Rubric breakdown", "", "| Category | Score |", "| --- | --- |");
  rubric.categories.forEach((category) => {
    lines.push(`| ${category.title} | ${category.earned}/${category.max} (${category.percent}%) |`);
  });
  lines.push("");

  lines.push("<details><summary>Every check</summary>", "");
  rubric.categories.forEach((category) => {
    lines.push(`### ${category.title}`, "");
    category.checks.forEach((check) => {
      const mark = check.status === "pass" ? "x" : " ";
      lines.push(`- [${mark}] **${check.label}** (${check.earned}/${check.weight}) - ${check.detail}`);
    });
    lines.push("");
  });
  lines.push("</details>", "");

  lines.push("---", "", "_Generated by GitGrade._");
  return lines.join("\n");
}

/** Triggers a client-side download without touching the network. */
export function downloadFile(filename, contents, type = "text/plain") {
  const url = URL.createObjectURL(new Blob([contents], { type }));
  const anchor = document.createElement("a");

  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();

  URL.revokeObjectURL(url);
}
