import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Check, Minus, X, ChevronDown } from "lucide-react";
import { scoreTone } from "../lib/format";

const STATUS_ICON = {
  pass: { Icon: Check, className: "text-good" },
  partial: { Icon: Minus, className: "text-warn" },
  fail: { Icon: X, className: "text-bad" },
};

function CheckRow({ check }) {
  const { Icon, className } = STATUS_ICON[check.status];
  return (
    <li className="flex items-start gap-2.5 py-1.5">
      <Icon className={`mt-0.5 size-4 shrink-0 ${className}`} aria-hidden="true" />
      <div className="min-w-0 flex-1">
        <p className="text-sm text-ink-100">{check.label}</p>
        <p className="text-xs text-ink-500">{check.detail}</p>
      </div>
      <span className="shrink-0 font-mono text-xs text-ink-500 tabular-nums">
        {check.earned}/{check.weight}
      </span>
    </li>
  );
}

function Category({ category, defaultOpen }) {
  const [open, setOpen] = useState(defaultOpen);
  const tone = scoreTone(category.percent);

  return (
    <div className="border-b border-white/5 last:border-b-0">
      <button
        type="button"
        onClick={() => setOpen((value) => !value)}
        aria-expanded={open}
        className="flex w-full items-center gap-3 py-3 text-left transition hover:opacity-90"
      >
        <span className="w-44 shrink-0 truncate text-sm font-medium">{category.title}</span>

        <span className="h-2 flex-1 overflow-hidden rounded-full bg-white/10">
          <motion.span
            className={`block h-full rounded-full ${tone.bg}`}
            initial={{ width: 0 }}
            animate={{ width: `${category.percent}%` }}
            transition={{ duration: 0.8, ease: "easeOut" }}
          />
        </span>

        <span className={`w-12 shrink-0 text-right font-mono text-sm tabular-nums ${tone.text}`}>
          {category.percent}%
        </span>
        <ChevronDown
          className={`size-4 shrink-0 text-ink-500 transition-transform ${open ? "rotate-180" : ""}`}
          aria-hidden="true"
        />
      </button>

      <AnimatePresence initial={false}>
        {open ? (
          <motion.ul
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden pb-3 pl-1"
          >
            {category.checks.map((check) => (
              <CheckRow key={check.label} check={check} />
            ))}
          </motion.ul>
        ) : null}
      </AnimatePresence>
    </div>
  );
}

export default function CategoryBreakdown({ rubric }) {
  return (
    <motion.section
      initial={{ opacity: 0, y: 24 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.45, delay: 0.05 }}
      className="card p-6"
    >
      <h2 className="text-sm font-semibold uppercase tracking-wider text-ink-300">Rubric breakdown</h2>
      <p className="mb-2 mt-1 text-xs text-ink-500">
        Computed from repository data, not generated by the model. Expand a row to see every check.
      </p>

      {rubric.categories.map((category, index) => (
        <Category key={category.key} category={category} defaultOpen={index === 0} />
      ))}
    </motion.section>
  );
}
